In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/telco_churn.csv')

In [ ]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [ ]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [ ]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3323.000000,3323.000000,3315.000000,3324.000000,3325.000000,3333.000000,3333.000000,3332.000000,3333.000000,3333.000000,3333.000000,3328.000000,3328.000000
mean,101.064806,437.182418,8.099010,179.787150,100.456214,30.557831,201.033935,100.110677,17.083540,200.872037,100.115246,9.039325,10.237294,4.479448,2.764588,1.563101
std,39.822106,42.371290,13.688365,54.419625,20.057356,9.255987,50.676652,19.932115,4.310668,50.573847,19.566710,2.275873,2.791840,2.461214,0.754086,1.315870
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.420000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.500000,114.000000,36.780000,235.325000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [ ]:
df.shape

(3333, 20)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3333 non-null   object
 1   Account length          3333 non-null   int64
 2   Area code               3333 non-null   int64
 3   International plan      3333 non-null   object
 4   Voice mail plan         3333 non-null   object
 5   Number vmail messages   3333 non-null   int64
 6   Total day minutes       3323 non-null   float64
 7   Total day calls         3323 non-null   float64
 8   Total day charge        3315 non-null   float64
 9   Total eve minutes       3324 non-null   float64
 10  Total eve calls         3325 non-null   float64
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3332 non-null   float64
 14  Total night charge      3333 non-null   float64
 15  Total intl minutes      3333 non-null   float64
 16  Total intl calls        3333 non-null   int64
 17  Total intl charge       3328 non-null   float64
 18  Customer service calls  3328 non-null   float64
 19  Churn                   3325 non-null   object
dtypes: float64(12), int64(4), object(4)
memory usage: 520.9+ KB

In [ ]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [ ]:
df['State'].nunique()

51

In [ ]:
df[(df['International plan']=="No")& (df['Customer service calls']>3)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
21,CO,77,408,No,No,0,NaN,NaN,NaN,169.9,121.0,14.44,209.6,64.0,9.43,5.7,6,1.54,5.0,True
48,ID,119,415,No,No,0,159.1,114.0,27.05,231.3,117.0,19.66,143.2,91.0,6.44,8.8,3,2.38,5.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280,AR,76,408,No,No,0,107.3,140.0,18.24,238.2,133.0,20.25,271.8,116.0,12.23,10.0,3,2.70,4.0,True
3287,KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True
3307,OK,172,408,No,No,0,203.9,109.0,34.66,234.0,123.0,19.89,160.7,65.0,7.23,17.8,4,4.81,4.0,False
3322,MD,62,408,No,No,0,321.1,105.0,54.59,265.5,122.0,22.57,180.5,72.0,8.12,11.5,2,3.11,4.0,True
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True

In [ ]:
df.iloc[12]

State                        IA
Account length              168
Area code                   408
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         104.9
Total eve calls            71.0
Total eve charge           8.92
Total night minutes       141.1
Total night calls         128.0
Total night charge         6.35
Total intl minutes         11.2
Total intl calls              2
Total intl charge          3.02
Customer service calls      1.0
Churn                     False
Name: 12, dtype: object

In [ ]:
df.iloc[3]

State                        OH
Account length               84
Area code                   408
International plan          Yes
Voice mail plan              No
Number vmail messages         0
Total day minutes         299.4
Total day calls            71.0
Total day charge           50.9
Total eve minutes          61.9
Total eve calls            88.0
Total eve charge           5.26
Total night minutes       196.9
Total night calls          89.0
Total night charge         8.86
Total intl minutes          6.6
Total intl calls              7
Total intl charge          1.78
Customer service calls      2.0
Churn                     False
Name: 3, dtype: object

In [ ]:
df.iloc[10:20]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False

In [ ]:
df.iloc[:,3]

0        No
1        No
2        No
3       Yes
4       Yes
       ...
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [ ]:
df.iloc[1:3,1:3]

   Account length  Area code
1             107        415
2             137        415

In [ ]:
df.loc[1:3]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False

In [ ]:
df.iloc[1:3]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False

In [ ]:
df.loc[1:4, ['Total day minutes', 'Total eve minutes']]

   Total day minutes  Total eve minutes
1              161.6              195.5
2              243.4              121.2
3              299.4               61.9
4              166.7              148.3

In [ ]:
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [ ]:
df.drop('Area code', axis=1)

,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,128,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,107,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,137,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,84,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,75,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,68,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,28,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,184,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,74,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [ ]:
df.columns

Index(['Account length', 'Area code', 'International plan', 'Voice mail plan',
       'Number vmail messages', 'Total day minutes', 'Total day calls',
       'Total day charge', 'Total eve minutes', 'Total eve calls',
       'Total eve charge', 'Total night minutes', 'Total night calls',
       'Total night charge', 'Total intl minutes', 'Total intl calls',
       'Total intl charge', 'Customer service calls', 'Churn'],
      dtype='object')

In [ ]:
df['New_column'] = df['Total day minutes'] + df['Total eve minutes']

In [ ]:
df.head()

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New_column
0,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,462.5
1,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,357.1
2,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,364.6
3,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,361.3
4,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,315.0

In [ ]:
df.iloc[0,12] = 58

In [ ]:
df['churn_binary'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

In [ ]:
df.head()

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New_column,churn_binary
0,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,...,244.7,58.0,11.01,10.0,3,2.70,1.0,False,462.5,0
1,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,...,254.4,103.0,11.45,13.7,3,3.70,1.0,False,357.1,0
2,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,...,162.6,104.0,7.32,12.2,5,3.29,0.0,False,364.6,0
3,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,...,196.9,89.0,8.86,6.6,7,1.78,2.0,False,361.3,0
4,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,...,186.9,121.0,8.41,10.1,3,2.73,3.0,False,315.0,0